# Generated by Django 4.0.5 on 2022-07-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('fragancia', models.CharField(max_length=30)),
                ('sexo', models.CharField(max_length=6)),
                ('tamaño', models.CharField(max_length=10)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='fragancia',
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='tamaño',
        ),
    ]
