# Generated by Django 3.2.12 on 2022-07-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crear_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('fragancia', models.CharField(max_length=30)),
                ('sexo', models.CharField(max_length=6)),
                ('tamaño', models.CharField(max_length=10)),
                ('precio', models.IntegerField()),
                ('descuento', models.CharField(max_length=10)),
                ('precio_final', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
